### ISSUE TITLE
Wrong link for predix-microservice-cf-rabbitmqconsumer

### ISSUE THREAD

**Issue by spikeforce** [PredixDev/predix-microservice-templates#1]
From the microservices table, the link for "predix-microservice-cf-rabbitmqconsumer" is pointing to the URL https://github.build.ge.com/adoption/rabbitmq-consumer-template.git that doesn't exist. Should it be https://github.com/PredixDev/rabbitmq-consumer-template?

**Comment by gstroup** [comment]
Yes, you are correct.  I'll fix this now.  Thanks!
